version: '3'

services:  
  mlflow-server:
    container_name: test-mlflow-server
    hostname: test-mlflow-server
    image: mlflow-test:mlflow-server
    build:
      context: ./mlflow-server
      dockerfile: DockerFile
    volumes:
      - ./mlflow-server/src:/src
      - ./s3:/src/s3
    ports:
      - 5000:5000
    networks:
      - global
      - dev-backend

  frontend-server:
    container_name: test-frontend-server
    hostname: test-frontend-server
    image: api-test:frontend-server
    build:
      context: ./frontend-server
      dockerfile: DockerFile
    volumes:
      - ./frontend-server/src:/src
    ports:
      - 8880:8888
    networks:
      - global
      - dev-backend

networks:
  global:
  dev-backend:
    driver: bridge